### ISSUE TITLE
warning in q_ts_biomass

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [BenWilliams-NOAA/groundfishr#6]
Just throws a warning msg but msg is confusing out of context. Easy fix!

https://github.com/BenWilliams-NOAA/groundfishr/blob/64a014bd1e40e7bfc480759ad038e84c1a938b27/R/q_ts_biomass.R#L18

Fix:
```
if (afsc_species[1] == 20510) { 
      .bio = sql_read(files[9])
    }
```

**Comment by BenWilliams-NOAA** [comment]
corrected in the q_ts_biomass file
