### ISSUE TITLE
naming conventions: "area", "survey", "region"

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [BenWilliams-NOAA/groundfishr#7]
This is just about consistency in naming conventions. `ts_age_comp()` uses `area = "goa"`, `ts_length_comp()` uses `survey = "goa"`, and `lls_length_comp()` uses `region = "goa"`. Not a big deal, but it through me off when troubleshooting.

When I get back from survey I'll check into GOA REBS dat file inconsistencies and check out the modeling running and plotting functions. Thank you so much! Great work on this stuff.

**Comment by BenWilliams-NOAA** [comment]
Changed all to "area" from region or survey.
